Инкремент 13
MihailSergeenkov/shortener pull request #14
Opened 2024-06-10 11:24 UTC by MihailSergeenkov

Добавление ошибки 409

2024-06-10 17:16 UTC, s-shpak requested changes

2024-06-10 17:16 UTC, s-shpak commented on internal/app/data/base.go
> +	mu   sync.RWMutex
Не знаю, зачем ты решил добавить мьютекс сейчас (их надо будет добавить на 4 спринте), но лучше добавить указатель на мьютекс, чтобы случайно его не скопировать (в Go это запрещено)

2024-06-10 17:16 UTC, s-shpak commented on internal/app/data/base.go
> +	s.mu.RLock()
Не, это плохо. Убери мьютексы, потом обсудим как с ними работать (спойлер: не используй `RWMutex`, хорошо знать о его существовании, но он не нужен в проекте)

2024-06-10 17:16 UTC, s-shpak commented on internal/app/data/db.go
> +	db, err := sql.Open("pgx", dbDSN)
Почему бы и здесь не воспользоваться пулом соединений ?

2024-06-10 17:16 UTC, s-shpak commented on internal/app/data/db.go
> +	ctx := context.Background()
Тут контекст тоже стоит передавать извне, создай его на самом верхнем уровне

2024-06-10 17:16 UTC, s-shpak commented on internal/app/data/db.go
> +	url, getErr := s.getShortURL(ctx, originalURL)
1. Здесь надо либо обойтись одним запросом к БД (см. ON CONFLICT), либо проверять ошибку, которая возвращает БД при попытке вставить уже существующую длинную ссылку и только потом доставать соответствующую короткую из БД
2. Если операция делает несколько запросов к БД, то их надо обернуть в транзакцию

2024-06-10 17:16 UTC, s-shpak commented on internal/app/data/db.go
> +			rErr := tx.Rollback(ctx)
Посмотри в материалах вебинара как лучше обрабатывать роллбэки (ты уже это используешь в некоторых местах в коде)

2024-06-10 17:16 UTC, s-shpak commented on internal/app/data/db.go
> +		_, err := tx.Exec(ctx, stmt, url.ShortURL, url.OriginalURL)
Для каждого URL ты отпарвляешь новый запрос в БД, это дорого. Используй Batch из pgx

2024-06-10 17:16 UTC, s-shpak commented on internal/app/handlers/ping.go
> +			w.WriteHeader(http.StatusInternalServerError)
А зачем ? Пусть пинг к inmemory и file хранилищам просто ничего не делает и возвращает nil ?

2024-06-11 07:52 UTC, MihailSergeenkov commented on internal/app/data/base.go
> +	mu   sync.RWMutex
В 12 инкременте в задании написано 
<img width="774" alt="image" src="https://github.com/MihailSergeenkov/shortener/assets/10576643/3783a39a-0df1-4f15-8a8d-8325e1174a21">
Ну и соотв. добавление в map новых элементов изначально не потокобезопасно. А мне для подсчета следующего айдишника (больше для файлового варианта БД), нужно знать текущей кол-во элементов в мапе. Если два потока одновременно увидят одинаковое кол-во элементов, то я в итоге получу задублированные айдишники. Как сделать потокобезопасный вариант подсмотрел в доке https://go.dev/blog/maps

Ну если нужно уберу, конечно. Но тогда условие задания будут выполнены не до конца.

2024-06-12 09:07 UTC, MihailSergeenkov commented on internal/app/data/base.go
> +	mu   sync.RWMutex
Убрал.

2024-06-12 09:07 UTC, MihailSergeenkov commented on internal/app/data/base.go
> +	s.mu.RLock()
Убрал

2024-06-12 09:08 UTC, MihailSergeenkov commented on internal/app/data/db.go
> +	db, err := sql.Open("pgx", dbDSN)
да, пул будет правильнее, поправил

2024-06-12 09:08 UTC, MihailSergeenkov commented on internal/app/data/db.go
> +	ctx := context.Background()
сделал

2024-06-12 09:17 UTC, MihailSergeenkov commented on internal/app/data/db.go
> +	url, getErr := s.getShortURL(ctx, originalURL)
Не совсем понимаю, чем может помочь ON CONFLICT, там же либо изменять запись, либо добавлять, либо ничего не делать. А в нашем случае нужно еще и вернуть короткую ссылку. Если не обновлять короткую ссылку, то и вернуть "старую"-новую не получится. А обновлять чисто по "бизнес" логике будет странноватым, мало ли кто ее себе сохранил? Т.е. получается за один запрос процесс не сделать. 
По поводу делать INSERT и проверять ошибку, а потом если норм, то доставлять остальные данные... не могу согласиться, что такая реализация будет понятнее для чтения другими разработчиками, админами БД (логи) и тд. В моей реализации (чуток поправил название метода и ее возврат), есть четкое понимание "бизнес" логики, сперва поверяем наличии длинной ссылки, и если ее нет создаем, а если есть возвращаем короткую. Никаких недопониманий возникнуть не должно, что этот код делает (так называемое ментальное программирование). По поводу оборачивания в транзакцию согласен, поправил.

2024-06-12 09:17 UTC, MihailSergeenkov commented on internal/app/data/db.go
> +			rErr := tx.Rollback(ctx)
сделал

2024-06-12 09:18 UTC, MihailSergeenkov commented on internal/app/data/db.go
> +		_, err := tx.Exec(ctx, stmt, url.ShortURL, url.OriginalURL)
сделал

2024-06-12 09:18 UTC, MihailSergeenkov commented on internal/app/handlers/ping.go
> +			w.WriteHeader(http.StatusInternalServerError)
поправил

2024-06-14 13:38 UTC, s-shpak commented on internal/app/data/db.go
> +	url, getErr := s.getShortURL(ctx, originalURL)
ОК, обойтись одним запросом точно можно. Если интересно, то попробуй понять как, мы разберем это сегодня на вебинаре. Если нет, то просто зарезолвь этот комментарий

По поводу второго предложения: предложенная реализация позволяет реже отправлять два запроса к БД, но эту оптимизацию можно оставить на будущее

2024-06-14 13:46 UTC, s-shpak requested changes

2024-06-14 13:46 UTC, s-shpak commented on internal/app/data/db.go
> +		rollbackTx(ctx, tx, s.logger)
См. здесь, как в `pgx` можно работать с транзакциями: https://pkg.go.dev/github.com/jackc/pgx#hdr-Transactions

2024-06-14 13:46 UTC, s-shpak commented on internal/app/data/db.go
> +	return s.pool.Ping(ctx) //nolint:wrapcheck // не нужно оборачивать, это делается на более верхнем уровне
Почему не надо оборачивать ? Оборачивать ошибки из сторонних пакетов правильно

2024-06-14 13:46 UTC, s-shpak commented on internal/app/data/db.go
> +	cErr := tx.Commit(ctx)
А где роллбэк ?

2024-06-16 13:54 UTC, MihailSergeenkov commented on internal/app/data/db.go
> +	url, getErr := s.getShortURL(ctx, originalURL)
Спасибо за пример с ON CONFLICT, с добавлением доп. поля получилось очень красиво, даже нельзя сказать костыльно) и код сильно сократился.

2024-06-16 13:54 UTC, MihailSergeenkov commented on internal/app/data/db.go
> +		rollbackTx(ctx, tx, s.logger)
ага, поправил

2024-06-16 13:55 UTC, MihailSergeenkov commented on internal/app/data/db.go
> +	return s.pool.Ping(ctx) //nolint:wrapcheck // не нужно оборачивать, это делается на более верхнем уровне
перепутал( почему-то посчитал, что уровнем выше уже оборачиваю( хотя правильнее, конечно на более нижнем уровне оборачивать.

2024-06-16 13:56 UTC, MihailSergeenkov commented on internal/app/data/db.go
> +	cErr := tx.Commit(ctx)
Утопил в метод ниже( что, конечно, не правильно(

2024-06-19 15:44 UTC, s-shpak approved these changes

2024-06-19 18:23 UTC, merged