Инкремент 15
MihailSergeenkov/shortener pull request #16
Opened 2024-06-20 14:59 UTC by MihailSergeenkov

2024-06-24 20:01 UTC, s-shpak requested changes
URL помеченные к удалению надо когда-то удалить. Предлагаю делать так: отмечаешь к удалению, создаешь го-рутину, которая будет этим заниматься, отвечаешь пользователю.

Дизайн компонента, который занимается удалением остается на твое усмотрение: он может работать периодически, например

2024-06-24 20:01 UTC, s-shpak commented on internal/app/common/common.go
> +type ContextValueKey string
Я бы делал ключ int и инициализировал при помощи iota, как здесь: https://stackoverflow.com/questions/40891345/fix-should-not-use-basic-type-string-as-key-in-context-withvalue-golint

Это делает работу с данными внутри контекста более эффективной

2024-06-24 20:01 UTC, s-shpak commented on internal/app/data/db.go
> +		`ALTER TABLE urls ADD COLUMN IF NOT EXISTS user_id VARCHAR(200)`,
Необходимо создавать схему при помощи миграции, см. здесь как: https://github.com/s-shpak/webinar-migrations

2024-06-24 20:01 UTC, s-shpak commented on internal/app/routes/auth.go
> +			authCookie, cookieErr := r.Cookie("AUTH_TOKEN")
```suggestion
			authCookie, err := r.Cookie("AUTH_TOKEN")
```

2024-06-24 20:01 UTC, s-shpak commented on internal/app/routes/auth.go
> +				if errors.Is(cookieErr, http.ErrNoCookie) {
Можно ли уменьшить вложенность здесь ?

2024-06-24 20:01 UTC, s-shpak commented on internal/app/services/services.go
> +func DeleteUserURLs(ctx context.Context, l *zap.Logger, s data.Storager, shortURLs []string) error {
На самом деле fan-in в задании ни к чему, его можно убрать (известная проблема контента, отправил сообщение авторам)

2024-06-24 20:01 UTC, s-shpak commented on internal/app/data/db.go
>  func (s *DBStorage) StoreShortURL(ctx context.Context, shortURL string, originalURL string) error {
Если пара ссылок помечена на удаление, то она не должна провоцировать коллизию

2024-06-25 08:15 UTC, MihailSergeenkov commented
> URL помеченные к удалению надо когда-то удалить. Предлагаю делать так: отмечаешь к удалению, создаешь го-рутину, которая будет этим заниматься, отвечаешь пользователю.
> 
> Дизайн компонента, который занимается удалением остается на твое усмотрение: он может работать периодически, например

ХМ, думал нужно просто мягкое удаление. А автотесты пройдут? они проверяют именно на пометку удаления... если я не поставлю хороший таймаут, то могу получи флакитест(

2024-06-26 07:17 UTC, MihailSergeenkov commented on internal/app/data/db.go
>  func (s *DBStorage) StoreShortURL(ctx context.Context, shortURL string, originalURL string) error {
Добавил условие на индекс

2024-06-26 07:17 UTC, MihailSergeenkov commented on internal/app/services/services.go
> +func DeleteUserURLs(ctx context.Context, l *zap.Logger, s data.Storager, shortURLs []string) error {
Убрал

2024-06-26 07:18 UTC, MihailSergeenkov commented on internal/app/routes/auth.go
> +				if errors.Is(cookieErr, http.ErrNoCookie) {
уменьшил на одну вложенность

2024-06-26 07:18 UTC, MihailSergeenkov commented on internal/app/routes/auth.go
> +			authCookie, cookieErr := r.Cookie("AUTH_TOKEN")
принял

2024-06-26 07:18 UTC, MihailSergeenkov commented on internal/app/data/db.go
> +		`ALTER TABLE urls ADD COLUMN IF NOT EXISTS user_id VARCHAR(200)`,
переделал

2024-06-26 07:18 UTC, MihailSergeenkov commented on internal/app/common/common.go
> +type ContextValueKey string
спасибо, поправил

2024-06-27 14:50 UTC, s-shpak requested changes
На получение сохраненной ссылки также должен влиять флаг `is_deleted`

2024-06-27 14:50 UTC, s-shpak commented on internal/app/data/migrations/00002_add_user_id_to_urls.down.sql
Мне кажется, что логичнее создать только одну миграцию: с моей т.з. каждая миграция - отедльная версия приложения. Версия приложения - рабочий код. Код не будет функциональным (не будет реалзиовывать ТЗ), если не выполнить все описанные тобой миграции, значит, лучше поместить все в одну миграцию

2024-06-27 17:13 UTC, MihailSergeenkov commented
> На получение сохраненной ссылки также должен влиять флаг `is_deleted`

Не совсем понял замечание. В задании сказано, что нужно отдавать статус Gone, в коде это есть https://github.com/MihailSergeenkov/shortener/pull/16/files#diff-39463c1a799dead618a35bafccb4601c3da4983dd053886aea03fcf5bd8713e0R31.

Какое влияние еще имеется ввиду?

2024-06-27 17:17 UTC, MihailSergeenkov commented on internal/app/data/migrations/00002_add_user_id_to_urls.down.sql
Согласен. Но добавление функциональности по юзеру было в отдельном задании, и соотв. в отдельно инкременте, т.е. в отдельном рабочем варианте приложения. Поэтому я и восстановил последовательность. Так-то можно было все в одну миграцию добавить...

2024-06-28 04:22 UTC, MihailSergeenkov commented on internal/app/data/migrations/00002_add_user_id_to_urls.down.sql
Объединил все в одну миграцию.

2024-06-30 11:18 UTC, s-shpak approved these changes

2024-06-30 18:19 UTC, merged