Инкремент 20
MihailSergeenkov/shortener pull request #21
Opened 2024-08-31 16:13 UTC by MihailSergeenkov

2024-09-03 09:39 UTC, s-shpak requested changes
Добавь в Readme.md информацию о том, как билдить приложение с заданными версией, датой и коммитом

2024-09-03 09:39 UTC, s-shpak commented on cmd/staticlint/main.go
> +func run(pass *analysis.Pass) (interface{}, error) {
1. Не проверяется, что вызов делается внутри пакета `main`
2. Слишком высокая вложенность, попробуй отрефакторить код, чтобы его было проще читать

2024-09-03 09:39 UTC, s-shpak commented on cmd/staticlint/main.go
> +		if file.Name.Name != "main" {
Функция `main` необязательно будет лежать в файле `main`

2024-09-03 09:39 UTC, s-shpak commented on cmd/staticlint/main.go
> +						if p.Name == "os" && selector.Sel.Name == "Exit" {
Проверять необходимо только вызов `Exit` внутри функции `main`

2024-09-03 19:04 UTC, MihailSergeenkov commented on cmd/staticlint/main.go
> +func run(pass *analysis.Pass) (interface{}, error) {
Сделал

2024-09-03 19:04 UTC, MihailSergeenkov commented on cmd/staticlint/main.go
> +		if file.Name.Name != "main" {
Сделал

2024-09-03 19:05 UTC, MihailSergeenkov commented on cmd/staticlint/main.go
> +						if p.Name == "os" && selector.Sel.Name == "Exit" {
Сделал

2024-09-03 19:05 UTC, MihailSergeenkov commented
В Readme.md добавил

2024-09-09 08:57 UTC, s-shpak approved these changes

2024-09-10 03:29 UTC, merged