Инкремент 25
MihailSergeenkov/shortener pull request #26
Opened 2024-09-26 12:25 UTC by MihailSergeenkov

2024-09-27 11:09 UTC, s-shpak requested changes

2024-09-27 11:09 UTC, s-shpak commented on README.md
> +grpcurl -plaintext localhost:3200 shortener.Shortener.Ping
Кстати, можно добавить SwaggerUI для отправки gRPC запросов. Здесь описано как: https://medium.com/@pointgoal/grpc-how-to-add-swagger-ui-on-grpc-466e5fd71097

Это не требуется, просто FYI. Комментарий можно зарезолвить

2024-09-27 11:09 UTC, s-shpak commented on internal/app/proto/shortener.proto
> +  rpc FetchUserURLs(google.protobuf.Empty) returns (FetchUserURLsResponse);
Лучше не использовать `google.protobuf.Empty` -- если тебе в будующем надо будет отправлять какое-то поле в запросе, то тебе не придется создавать новую версию интерфейса

2024-09-28 07:28 UTC, MihailSergeenkov commented on README.md
> +grpcurl -plaintext localhost:3200 shortener.Shortener.Ping
ага, понял, интересно)

2024-09-28 07:28 UTC, MihailSergeenkov commented on internal/app/proto/shortener.proto
> +  rpc FetchUserURLs(google.protobuf.Empty) returns (FetchUserURLsResponse);
Ага, понял. 
Спасибо, поправил.

2024-09-28 08:46 UTC, s-shpak approved these changes

2024-09-28 12:51 UTC, merged