Пятый инкремент
MihailSergeenkov/shortener pull request #5
Opened 2024-05-06 13:23 UTC by MihailSergeenkov

Добавить возможность конфигурации через глобальные переменные

2024-05-07 07:58 UTC, s-shpak requested changes
Добавь `golangci-lint` в Github Actions как описано здесь: https://github.com/s-shpak/praktikum-golangci-lint?tab=readme-ov-file#настройка-github-actions

2024-05-07 07:58 UTC, s-shpak commented on cmd/shortener/main.go
> +	fmt.Println("Running server on", config.Params.RunAddr)
Используй `log` вместо `fmt`. Также лучше использовать `Printf`

2024-05-07 07:58 UTC, s-shpak commented on cmd/shortener/main.go
> +	r := chi.NewRouter()
Я бы вынес настройку роутера в отдельную функцию в `internal`

2024-05-07 07:58 UTC, s-shpak commented on internal/app/config/main.go
Почему этот файл называется `main.go` ? Если в пакете один файл то его, как правило, называют также, как пакет

2024-05-07 07:58 UTC, s-shpak commented on internal/app/config/main.go
> +	"github.com/caarlos0/env/v6"
Есть 11-ая версия

2024-05-07 07:58 UTC, s-shpak commented on internal/app/storage/urls.go
> +var urls = make(map[string]string, 100)
Глобальные переменные не нужны

2024-05-07 07:58 UTC, s-shpak commented on internal/app/storage/urls.go
> +	bytes := make([]byte, 4)
4 байта - очень мало, начни с 8

2024-05-07 07:58 UTC, s-shpak commented on internal/app/storage/urls.go
> +	urls[h] = u
Что если такой `shortURL` уже есть ?

2024-05-07 07:58 UTC, s-shpak commented on internal/app/storage/urls.go
> +		return "", fmt.Errorf("%w for hash %s", ErrURLNotFound, h)
Это не хеш

2024-05-07 07:58 UTC, s-shpak commented on internal/app/handlers/add.go
> +		w.WriteHeader(http.StatusBadRequest)
Это не `BadRequest`, скорее `InternalServerError`

2024-05-07 07:58 UTC, s-shpak commented on internal/app/handlers/add.go
> +		w.WriteHeader(http.StatusUnprocessableEntity)
Интересный статус, но это тоже скорее `InternalServerError`

2024-05-07 07:58 UTC, s-shpak commented on internal/app/handlers/add.go
> +	url := fmt.Sprintf(`%s/%s`, config.Params.BaseURL, h)
Лучше используй `https://pkg.go.dev/net/url#JoinPath`

2024-05-07 07:58 UTC, s-shpak commented on internal/app/handlers/add_test.go
> +				code: 201,
`201` - магическое число, используй это: https://go.dev/src/net/http/status.go

2024-05-07 07:58 UTC, s-shpak commented on internal/app/handlers/add_test.go
> +			if test.want.code == 201 {
А зачем эта проверка, ведь в случае ошибки Body может быть каким-то (возможно даже пустым)

2024-05-07 07:58 UTC, s-shpak commented on internal/app/handlers/fetch.go
> +	re := regexp.MustCompile(`^/\w{8}$`)
Не нужно, роутер делает это за тебя

2024-05-07 07:58 UTC, s-shpak commented on internal/app/handlers/fetch.go
> +		w.WriteHeader(http.StatusInternalServerError)
В случае `InternalServerError` ошибку надо логировать

2024-05-07 13:53 UTC, MihailSergeenkov commented
Спасибо! Все замечания поправлю.

2024-05-08 11:24 UTC, MihailSergeenkov commented on internal/app/config/main.go
попутал( почему-то показалось, что должно быть `main.go`

2024-05-08 11:25 UTC, MihailSergeenkov commented on internal/app/storage/urls.go
> +	urls[h] = u
добавил проверку

2024-05-10 14:21 UTC, s-shpak requested changes
Не резолвь, пожалуйста, комментарии: я буду делать это сам, чтобы лучше понимать, что именно было изменено

2024-05-10 14:21 UTC, s-shpak commented on internal/app/handlers/add.go
> +			log.Println(err)
Ошибки из сторонних пакетов лучше оборачивать, чтобы добавлять больше контекста: `log.Printf("failed to construct URL: %v", err)`

2024-05-10 14:21 UTC, s-shpak commented on internal/app/storage/urls.go
> +var initSize = 100
Это константы

2024-05-10 14:21 UTC, s-shpak commented on internal/app/storage/urls.go
> +		if _, ok := urls[id]; ok {
Что если такая короткая ссылка уже есть ?

2024-05-11 07:39 UTC, MihailSergeenkov commented
> Не резолвь, пожалуйста, комментарии: я буду делать это сам, чтобы лучше понимать, что именно было изменено

Ага, хорошо, тогда буду просто плюсики ставить для себя.

2024-05-11 07:51 UTC, MihailSergeenkov commented on internal/app/storage/urls.go
> +		if _, ok := urls[id]; ok {
Может быть я неправильно организовал бесконечный цикл?
В моем понимании, если такой ключ уже есть, то выполнится `continue`, и сгенериться новый ключ.

В целом, что даже на бою это будет редкой ситуацией, тк попасть несколько раз на уже существующий ключ крайняя удача, даже если сервисом будут пользоваться миллионы, а ключей мы можем сгенерировать несколько квадриллионов. Думаю в будущем, если бы системы мониторинга показали увеличение времени генерирования (из-за 5-10 проходов цикла), то можно было бы добавить время жизни ссылки.

2024-05-11 08:06 UTC, MihailSergeenkov commented on internal/app/handlers/add.go
> +			log.Println(err)
+

2024-05-11 08:07 UTC, MihailSergeenkov commented on internal/app/storage/urls.go
> +var initSize = 100
`+`

2024-05-11 08:07 UTC, MihailSergeenkov commented on internal/app/storage/urls.go
> +		if _, ok := urls[id]; ok {
Пока ничего не добавил.

2024-05-11 13:31 UTC, s-shpak requested changes

2024-05-11 13:31 UTC, s-shpak commented on internal/app/storage/urls.go
> +		if _, ok := urls[id]; ok {
Сорри, не туда посмотрел, когда оставлял комментарий.

С такой проверкой проблем нет. Хотелось бы предложить сделать ограниченное число попыток генерации уникальной `shortURL`. Если не получается, то просто вернуть клиенту `Internal Server Error`. Вероятность сгенерировать одинаковые ключи мала, но если в нашем сервисе появится баг, который будет приводить к коллизиям, с таким решением мы это быстрее заметим

2024-05-11 19:27 UTC, MihailSergeenkov commented on internal/app/storage/urls.go
> +		if _, ok := urls[id]; ok {
Ограничил 5-ю попытками, будет генерироваться ошибка.

2024-05-13 21:25 UTC, s-shpak approved these changes

2024-05-15 07:41 UTC, merged