Инкремент 9
MihailSergeenkov/shortener pull request #9
Opened 2024-05-26 10:37 UTC by MihailSergeenkov

Добавлена работа с файлом данных

2024-05-28 06:12 UTC, s-shpak commented on internal/app/logger/logger.go
> +var Log *zap.Logger = zap.NewNop()
Я бы не создавал глобальную переменную, а передавал бы конкретный инстанс логгера туда, где он нужен

2024-05-28 06:35 UTC, s-shpak requested changes

2024-05-28 06:35 UTC, s-shpak commented on internal/app/logger/logger.go
> +func (r *loggingResponseWriter) WriteHeader(statusCode int) {
А что если `WriteHeader` не будет вызван ? Какой статус-код залогируется ?

2024-05-28 06:35 UTC, s-shpak commented on internal/app/logger/logger.go
> +var Log *zap.Logger = zap.NewNop()
Я бы не создавал глобальную переменную, а передавал бы конкретный инстанс логгера туда, где он нужен

2024-05-28 06:35 UTC, s-shpak commented on internal/app/logger/logger.go
> +func WithRequestLogging(next http.Handler) http.Handler {
Это не относится к логгированию, а относится к `REST API`, потому лучше поместить эту логику рядом с роутером и другими `middleware`

2024-05-28 06:35 UTC, s-shpak commented on internal/app/routes/routes.go
> +	api_handlers "github.com/MihailSergeenkov/shortener/internal/app/handlers/api"
Кажется, что давать псевдоним импорту здесь не нужно

2024-05-28 06:35 UTC, s-shpak commented on internal/app/routes/gzip.go
> +func (c *compressWriter) Header() http.Header {
Если встроить `Writer` в `compressWriter` при помощи композиции, то этот метод не надо будет определять

2024-05-28 06:35 UTC, s-shpak commented on internal/app/routes/gzip.go
> +	if statusCode < http.StatusMultipleChoices {
А вот здесь логично использовать не `StatusMultipleChoices`, а просто 300: иначе неясно, почему мы как-то особенно обраатываем статус `StatusMultipleChoices`

2024-05-28 06:35 UTC, s-shpak commented on internal/app/routes/gzip.go
> +	if err := c.r.Close(); err != nil {
`c.r` и `c.zr` - независимые ридеры, ошибка при закрытии одного не должна влиять на закрытие другого

2024-05-28 06:35 UTC, s-shpak commented on internal/app/handlers/api/add.go
Не очень понимаю структуру: зачем ты создал подпакет для этого функционала ?

2024-05-28 06:35 UTC, s-shpak commented on internal/app/handlers/api/add.go
> +			w.WriteHeader(http.StatusInternalServerError)
Это скорее `BadRequest`

2024-05-28 06:35 UTC, s-shpak commented on internal/app/handlers/api/add.go
> +			log.Printf("failed to read request body: %v", err)
Используй один и тот же логгер (тот, который ты используешь в middleware) везде в программе

2024-05-28 06:35 UTC, s-shpak commented on internal/app/data/data.go
> +	FileStoragePath string
Мне не очень нравится, как ты имплементировал это сейчас. Добавление записи в файл не должно менять код `in-memory` хранилища

Хотелось бы, чтобы:

1. Из конструктора хранилища возвращался объект общего интерфейса
2. Существовало две имплементации харинилища - in-memory и файловая
3. Файловое хранилище было оберткой надо in-memory: то есть встаривало бы in-memory при помощи композиции

В итоге сервису должно быть безразлично, сохраняем ли мы данные в файл или нет.

Если что-то непонятно из этого - уточни в пачке

2024-05-28 06:35 UTC, s-shpak commented on internal/app/data/data.go
> +func generateShortURL() (string, error) {
Возможно, я забыл упомянуть об этом на первом ревью, но хранилище не должно заниматься генерацией коротких URL. Зарефактори код так, чтобы хранилище только сохраняло и доставало данные, а бизнес-логика делала бы все остальное

2024-05-28 06:35 UTC, s-shpak commented on internal/app/data/data.go
> +	URLs            map[string]URL
Зачем экспортировать поля этой структуры ?

2024-05-28 08:09 UTC, MihailSergeenkov commented
Спасибо! Комменты поправлю, на вопросы отвечу.

2024-05-28 09:04 UTC, MihailSergeenkov commented on internal/app/logger/logger.go
> +func (r *loggingResponseWriter) WriteHeader(statusCode int) {
даа, в текущей реализации получится 0. Сделаю по-умолчанию 200, т.е. тот же статус-код, если не был вызван `WriteHeader`.

2024-05-28 15:38 UTC, MihailSergeenkov commented on internal/app/routes/gzip.go
> +func (c *compressWriter) Header() http.Header {
Может быть не туда смотрю, или не совсем понимаю, как правильно сделать.
Попробовал сделать по сути в лоб, но не получилось, тк мне также нужно переопределить `WriteHeader`, и если я не слелаю через композицию, то тогда получу рекурсивный вызов (ошибка infinite recursive call (sa5007) go-staticcheck). Поэтому в этом случае я сделал через `w  http.ResponseWriter`.

2024-05-28 15:40 UTC, MihailSergeenkov commented on internal/app/routes/routes.go
> +	api_handlers "github.com/MihailSergeenkov/shortener/internal/app/handlers/api"
Делал для читабельности года, что типо тоже хендлер) скорее это из Ruby мира, где в названия добавляешь больше информации, тк нет строгих типов) Из-за последующего коммента убрал совсем.

2024-05-28 15:41 UTC, MihailSergeenkov commented on internal/app/handlers/api/add.go
Убрал в основной.
Думал таким способом выделить апишные хендлеры.

2024-05-28 15:42 UTC, MihailSergeenkov commented on internal/app/logger/logger.go
> +var Log *zap.Logger = zap.NewNop()
`+`

2024-05-28 15:42 UTC, MihailSergeenkov commented on internal/app/logger/logger.go
> +func WithRequestLogging(next http.Handler) http.Handler {
`+`

2024-05-28 15:42 UTC, MihailSergeenkov commented on internal/app/routes/gzip.go
> +	if statusCode < http.StatusMultipleChoices {
`+`

2024-05-28 15:43 UTC, MihailSergeenkov commented on internal/app/routes/gzip.go
> +	if err := c.r.Close(); err != nil {
`+`

2024-05-28 15:43 UTC, MihailSergeenkov commented on internal/app/handlers/api/add.go
> +			w.WriteHeader(http.StatusInternalServerError)
`+`

2024-05-28 15:43 UTC, MihailSergeenkov commented on internal/app/handlers/api/add.go
> +			log.Printf("failed to read request body: %v", err)
`+`

2024-05-28 15:43 UTC, MihailSergeenkov commented on internal/app/data/data.go
> +	FileStoragePath string
`+`

2024-05-28 15:43 UTC, MihailSergeenkov commented on internal/app/data/data.go
> +func generateShortURL() (string, error) {
`+`

2024-05-28 15:45 UTC, MihailSergeenkov commented on internal/app/data/data.go
> +	URLs            map[string]URL
Грязный хак для создания инстансов в тестах(( чтобы не вводить интерфейсы.
Но в силу другого коммента все-таки их ввел и поправил.

2024-05-28 15:45 UTC, MihailSergeenkov commented on internal/app/logger/logger.go
> +func (r *loggingResponseWriter) WriteHeader(statusCode int) {
`+`

2024-05-29 16:07 UTC, s-shpak requested changes

2024-05-29 16:07 UTC, s-shpak commented on internal/app/data/base.go
> +func (s *BaseStorage) AddURL(originalURL string) (models.URL, error) {
Все еще не до конца развязали бизнес-логику и слой хранения данных. Правильнее будет определить интерфейс хранилища как 

```go
StoreShortURL(shortURL string, longURL string) error
GetFullURL(shortURL string) (string, error)
```

Тогда слой взаимодействия с хранилищем занимается исключительно сохранением и извлечением данных, а на уровне бизнес-логики находится все остальное.

Сорри, что не обсудили это на первом ревью

2024-05-29 16:07 UTC, s-shpak commented on internal/app/data/file.go
> +	encoder := json.NewEncoder(file)
Инициализируй переменные ближе к месту их использования

2024-05-29 16:07 UTC, s-shpak commented on internal/app/routes/gzip.go
> +func (c *compressWriter) Header() http.Header {
Чтобы не входить в бесконечную рекурсию при встраивании WriteHeader надо определять так:

```go
func (c *compressWriter) WriteHeader() {
    // bla-bla-bla
    c.Wrtier.WriteHeader()  // это вызов метода WriteHeader объекта Writer
    // bla-bla-bla
}
```

Подумай, откуда возникала бесконечная рекурсия

2024-05-30 15:04 UTC, MihailSergeenkov commented on internal/app/data/base.go
> +func (s *BaseStorage) AddURL(originalURL string) (models.URL, error) {
Ага, сделал, как написал.
Но у меня было сильное желание, все-таки при добавлении возвращать не только ошибку, но и модельку структуры данных. Также и при получении урла, получать не строку, а модельку структуры данных.
Как бы моделька URL больше относится к слою хранения) не знаю, насколько правильно это)

2024-05-30 15:04 UTC, MihailSergeenkov commented on internal/app/data/file.go
> +	encoder := json.NewEncoder(file)
`+`

2024-05-30 15:05 UTC, MihailSergeenkov commented on internal/app/routes/gzip.go
> +func (c *compressWriter) Header() http.Header {
`+` 
даа, почему рекурсия получилась, понятно) и почему бесконечная тоже)

2024-05-30 18:15 UTC, s-shpak approved these changes

2024-05-31 09:41 UTC, merged